---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Add Hosts to Group
      add_host:
        hostname: "10.42.0.14"
        groups: test

- name: Test Var
  hosts: 10.42.0.14
  gather_facts: no

  tasks:
    - debug:
        msg: "{{ test_var }}"
