---
- hosts: localhost
  gather_facts: no

  tasks:
    - debug:
        msg: "{{ test_var2 }}"
    - name: Add Hosts to Group
      add_host:
        hostname: "10.42.0.27"
        groups: test-group

- name: Print test_var
  hosts: 10.42.0.27
  gather_facts: no

  tasks:
    - debug:
        msg: "{{ test_var1 }}"
    - debug:
        msg: "{{ test_var2 }}"
